# Generated by Django 5.2.1 on 2025-05-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_delete_category_alter_fingerprintdata_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorfingerprint',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorfingerprint',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorfingerprint',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorfingerprint',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorfingerprint',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorfingerprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
