# Generated by Django 5.2.1 on 2025-05-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_visitorfingerprint_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FingerprintData',
        ),
    ]
