# Generated by Django 5.2.1 on 2025-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_delete_fingerprintdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorfingerprint',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitorfingerprint',
            name='screen_height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitorfingerprint',
            name='screen_width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
